[package]
name = "atomic-pool"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[features]
std = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[dependencies]
atomic-polyfill = "0.1.1"
as-slice            = { version = "0.1.4" }
stable_deref_trait  = { version = "1.2.0", default-features = false }

defmt = { version = "0.2.0", optional = true }
log = { version = "0.4.11", optional = true }
